version: '3.4'
name: unitofwork_container
services:
  unitofwork:
    container_name: unitofwork
    image: ${DOCKER_REGISTRY-}unitofwork
    build:
      context: UnitOfWork
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - '1433:1433'    
    expose:
      - 1433